a=int(input("Enter The Marks Of First Subject:"))
b=int(input("Enter The Marks Of Second Subject:"))
c=int(input("Enter The Marks Of Third Subject:"))
print("Average Of These Marks Is:",(a+b+c)/3)
print("Percentage Of These Marks Is:",(a+b+c)/3)